# Final Project: Data Analysis and Machine Learning Pipeline


## Overview

In this project, you will work with a synthetic dataset and apply the full data science workflow:

1. Data exploration and preparation using Pandas
2. Data cleaning and transformation
3. Exploratory Data Analysis (EDA) and visualization
4. Supervised machine learning using Scikit-learn
5. Model evaluation, comparison, and tuning

The goal is not just to build models, but to understand the impact of data quality, model choice, and evaluation techniques.

## Choose a Dataset

Choose one dataset from the list below.

Dataset Options:
- `bank_loan.csv`
- `ecommerce_customer_behavior.csv`
- `employee_attrition.csv`
- `employee_attrition.csv`
- `hospital_readmission.csv`
- `house_prices.csv`
- `telecom_customer.csv`

## Final Deliverables

### Submit:

1. **Jupyter Notebook**
- Ensure your notebook is well-organized, using multiple cells to separate different tasks and improve readability.
- Include clear, well-commented code throughout.
- Where required, provide a short written analysis using Markdown cells to explain your approach, results, and key insights.

________
# Part 1: Data Cleaning and Preparation
### Due Date : Wednesday April 8th at 11:59pm
## Step 1 – Load and Understand the Dataset (Pandas)

### Tasks

1. Load the libraries you will need.
2. Load the dataset into a Pandas DataFrame.
3. Display:
- First and last 5 rows
- Shape of the dataset
- General information of the data set.
    -  Write a analysis summary of what this gives you.
    -  Note if there are any missing values and in which columns.
  
3. Generate summary statistics for numerical columns.

In [2]:
#Import the libraries
import pandas as pd
import numpy as np

In [3]:
#Step 1: Specify File Path
file_path = 'fitness_tracker.csv'

#Step 2: Read CSV file
df=pd.read_csv(file_path)
df=pd.DataFrame(df)

In [4]:
# Display
# First and last 5 rows
df.head(5)

,user_id,age,steps_per_day,active_minutes,sleep_hours,calories_burned,activity_segment
0,1,40.0,11524.0,100.7,7.82,2594.2,Highly Active
1,2,34.0,2363.0,24.0,7.02,1714.8,LIGHT
2,3,41.0,NaN,79.9,NaN,2202.9,light activity
3,4,50.0,7875.0,90.5,7.59,2290.2,moderately active
4,5,33.0,8048.0,69.6,6.64,2238.8,moderately active

In [5]:
# Get the shape of the DataFrame (attribute)
df.shape

(12120, 7)

In [6]:
# summary
df.info()

# There're 12120 rows and 7 columns. 
# There are missing values in age, steps_per_day, active_minutes,sleep_hours, and calories_burned,
# because their Non-Null Count are less than 12120
# Except user_id is an int and activity_segment is an object, all other varaibles are numeric

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12120 entries, 0 to 12119
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           12120 non-null  int64
 1   age               11997 non-null  float64
 2   steps_per_day     12000 non-null  float64
 3   active_minutes    12000 non-null  float64
 4   sleep_hours       11999 non-null  float64
 5   calories_burned   11999 non-null  float64
 6   activity_segment  12120 non-null  object
dtypes: float64(5), int64(1), object(1)
memory usage: 662.9+ KB

In [8]:
# Print the summary statistics of the dataframe using describe()
# Note: if we simply using df.describe(), it will summarize the int column user_id, 
# user_id is a categorical varaible, there's no meaning to summarize mean, std, min, max....
# we only want to get a stats summary of numeric variable
summary=df.describe(include=['float'])
summary

,age,steps_per_day,active_minutes,sleep_hours,calories_burned
count,11997.000000,12000.000000,12000.000000,11999.000000,11999.000000
mean,35.138201,8050.005167,76.832542,7.202662,2270.282474
std,9.622011,2989.603739,25.949091,1.083675,262.383609
min,18.000000,1000.000000,5.000000,4.000000,1500.000000
25%,28.000000,5984.750000,58.900000,6.470000,2090.000000
50%,35.000000,8042.000000,76.700000,7.200000,2271.900000
75%,42.000000,10085.000000,94.500000,7.940000,2447.200000
max,74.000000,23976.000000,175.900000,10.000000,3387.600000

In [9]:
# Check the unique elements in activity_segment-> spelling is messy
pd.unique(df['activity_segment'])

array(['Highly Active', 'LIGHT', 'light activity', 'moderately active',
       'Moderate', 'Moderately Active', 'HIGHLY ACTIVE', 'Lightly Active',
       'highly active'], dtype=object)

In [10]:
# Check the unique individual ID  -> only 12000 individual but 12120, there might be duplicates
pd.unique(df['user_id'])

array([    1,     2,     3, ..., 11998, 11999, 12000], dtype=int64)

## Step 2 – Data Slicing, Subsetting, and Grouping

### Tasks

1. Make a function for each of the following tasks:
    - Select a subset of columns relevant for analysis.
    - Filter rows using logical conditions.
    - Group the data by at least one categorical column.
    - Calculate statistics for each group:
        - Mean
        - Count
        - Standard deviation
  
5. Briefly explain why you made each choice in this step. Describe why the selected columns are relevant to the problem, why specific filtering conditions were applied, and why you grouped the data using a particular categorical variable. Explain how calculating the mean, count, and standard deviation helps compare groups, understand typical behavior, assess group size, and measure variability. Conclude with one or two sentences summarizing what these statistics reveal about the data.
- Note if there are any inconsistencies in the data, this will help you in the next step.

In [48]:
# Suppose: I'm intertesting to see if there's a significant difference in sleep_hours 
# among different active satatus for middle aged (45-65) people
# Make a function called Mid_age_sleep

def Mid_age_sleep(df):
    # I selected the variables age, sleep_hours, and activity_segment 
    # because they are directly relevant to the research question. 
    # Age is needed to define the target population (middle-aged individuals), 
    # sleep_hours is the outcome of interest, and activity_segment represents
    # the grouping variable used to compare different activity levels.
    
    subset1=subset1 = df[['age', 'sleep_hours', 'activity_segment']]
    
    # I filtered the dataset to include only individuals aged between 45 and 65, 
    # which I defined as the middle-aged group. 
    #This allows the analysis to focus specifically on this population 
    # and avoids confounding effects from younger or older age groups.
    
    subset2=subset1[(subset1['age']>=45) & (subset1['age']<=65)]
    
    # I grouped the data by activity_segment to compare sleep patterns across different activity levels. 
    # This grouping helps identify whether activity status is associated with differences in sleep behavior.
    subset2_group= subset2.groupby('activity_segment')
    
    # Mean: Used to measure the average sleep hours and age within each activity group, 
    # providing insight into typical behavior.
    subset2_group_mean=subset2_group.mean(numeric_only=True)
    
    # Count: Indicates the number of individuals in each group, 
    # helping assess the reliability and representativeness of the results.
    subset2_group_count=subset2_group.count() 
    
    # Sd: Measures variability in sleep hours and age,
    # showing how consistent or spread out the values are within each group. 
    subset2_group_sd=subset2_group.std()

    print("Mean age and sleep time for different activity status:")
    print(subset2_group_mean)
    print("\nCount for each activity status:")
    print(subset2_group_count)
    print("\nStandard deviation for each activity status:")
    print(subset2_group_sd)

    return

In [49]:
Mid_age_sleep(df)

Mean age and sleep time for different activity status:
                         age  sleep_hours
activity_segment
HIGHLY ACTIVE      49.913265     7.193077
Highly Active      49.943750     7.176125
LIGHT              49.443114     7.406928
Lightly Active     50.232955     7.255087
Moderate           49.332298     7.157072
Moderately Active  49.785124     7.166233
highly active      49.706587     7.317305
light activity     49.448087     7.276758
moderately active  49.820261     7.208272

Count for each activity status:
                   age  sleep_hours
activity_segment
HIGHLY ACTIVE      196          195
Highly Active      160          160
LIGHT              167          166
Lightly Active     176          173
Moderate           322          321
Moderately Active  363          361
highly active      167          167
light activity     183          182
moderately active  306          301

Standard deviation for each activity status:
                        age  sleep_hours
activity_segment
HIGHLY ACTIVE      4.099735     1.128127
Highly Active      4.517258     1.095873
LIGHT              4.132744     1.012421
Lightly Active     4.398343     1.081744
Moderate           3.812361     1.044517
Moderately Active  4.402172     1.051589
highly active      4.553975     1.157634
light activity     3.993991     1.066889
moderately active  4.355932     1.117333

The results show that the average age across all activity groups is approximately 50, and the average sleep duration is around 7.2 hours.  These values are very similar across groups, suggesting that activity status may not significantly influence average sleep time within this middle-aged population. -> need further stats hypothesis testing. Most individuals fall into the Moderately Active group, indicating that this category has the largest sample size. The standard deviation for age is around 4 years, and for sleep duration it is about 1 hour across all groups. This suggests that variability is relatively consistent regardless of activity level. However, the Moderately Active group shows slightly higher standard deviation values, which may indicate greater variation in both age and sleep patterns within this group.

## Step 3 – Data Cleaning and Preparation
### Tasks
1. Identify missing values and report how many exist per column.
2. Handle missing values using one of these methods (Explain why you chose the method):
- Dropping
- Filling with mean/median/mode
  
3. Detect and handle outliers using one of these three methods:
   - Removing Outliers
   - Capping
   - Using sklearn pipeline

*Explain why you chose the method and why is better for your analysis*

4. Identify and remove duplicate records.
5. Fix inconsistent data in a categorical column:
- Standardize text values
- Convert data types if necessary

6. **Re-run the functions from Step 2** using the cleaned dataset. Compare the statistical results with those from the original, unclean dataset. Briefly describe how the statistics changed and explain how cleaning and preparing the data improves the accuracy and reliability of your analysis.

In [21]:
# In step 1, we have identify all the missing values are in numeric cloumns from df.info(). 
# 123 missing values in age, 120 in steps_per_day & active_minutes, and 121 in sleep_hours & calories_burned
# Around 120 missing values over 12k data, it's not a big protion (<= 5%) of data, I'd prefer to drop the missing values, 
# so the future stats models can be more acuurate 

df_cleaned = df.dropna()
df_cleaned.shape

# Also the result shows that rows are reduced to 11527 from  12120, we removed 4.8% of the data, for the rule of thrumb, it's still less than 5%.
# So it's okay to remove them than trying to filling them with 0

(11527, 7)

In [23]:
# In statistical analysis, we don't normally remove an outlier even after fitting the model
# The IRQ analysis is more for EDA, where we can observe outlier for each varaible. Note: bar plot can show Q1, Q2, Q3,IQR, and outliers.
# If we find some extreme outlier, we'll get back to do quality control analysis.
# Here, I'll just cap them. Let's define a function called handle_outliers. 

def handle_outliers(df):
    df_capped = df.copy()
    
    for column in df_capped.columns:
        if np.issubdtype(df_capped[column].dtype, np.number):
            q1 = df_capped[column].quantile(0.25)
            q3 = df_capped[column].quantile(0.75)
            iqr = q3 - q1
            
            lower_bound = q1 - 1.5 * iqr
            upper_bound = q3 + 1.5 * iqr

            # Note because I also want to create new columns, I don't want to overwrite the original column, I use df_capped[column + '_capped']
            df_capped[column + '_capped'] = np.where(
                df_capped[column] > upper_bound, upper_bound,
                np.where(df_capped[column] < lower_bound, lower_bound, df_capped[column])
            )
    
    return df_capped

In [25]:
df_capped=handle_outliers(df_cleaned)
df_capped.head(5)

,user_id,age,steps_per_day,active_minutes,sleep_hours,calories_burned,activity_segment,user_id_capped,age_capped,steps_per_day_capped,active_minutes_capped,sleep_hours_capped,calories_burned_capped
0,1,40.0,11524.0,100.7,7.82,2594.2,Highly Active,1.0,40.0,11524.0,100.7,7.82,2594.2
1,2,34.0,2363.0,24.0,7.02,1714.8,LIGHT,2.0,34.0,2363.0,24.0,7.02,1714.8
3,4,50.0,7875.0,90.5,7.59,2290.2,moderately active,4.0,50.0,7875.0,90.5,7.59,2290.2
4,5,33.0,8048.0,69.6,6.64,2238.8,moderately active,5.0,33.0,8048.0,69.6,6.64,2238.8
5,6,33.0,8541.0,75.8,6.81,2305.2,Moderate,6.0,33.0,8541.0,75.8,6.81,2305.2

In [29]:
# In step 1, we also notice the potential duplicates by seeing the output from pd.unique(df['user_id'])

duplicate_row=df_capped[df_capped.duplicated()]
print("duplicates rows: \n",duplicate_row)

df_without_duplicates=df_capped.drop_duplicates()
print("Data frame withiout duplicates: \n",df_without_duplicates)

duplicates rows:
        user_id   age  steps_per_day  active_minutes  sleep_hours  \
12009     1174  34.0         9527.0            85.7         6.94
12011     2489  35.0         5078.0            42.9         7.81
12018    10283  45.0         5075.0            36.2         7.33
12022     2228  29.0         7298.0            71.5         8.21
12023     4641  43.0         8239.0            83.3         5.46
12024     3506  21.0         7799.0            79.8         6.51
12025     8549  31.0         7585.0            79.7         5.73
12028    11223  34.0         7697.0            63.5         7.03
12030    11788  46.0        11207.0           102.4         6.31
12032     5794  36.0         6935.0            69.1         7.21
12033      823  58.0         8581.0            83.4         6.94
12035     4804  28.0         6000.0            68.4         8.04
12039    10897  20.0        10445.0            99.7         6.15
12047     8102  28.0         5629.0            77.2         6.79
12048     6284  45.0        11049.0           106.4         6.94
12049     1990  39.0         4012.0            42.6         7.21
12051     9134  38.0         9471.0            94.1         7.83
12055     7183  42.0        12215.0           113.8         8.30
12056     1417  36.0         1885.0            32.2         7.48
12059     1514  18.0         9015.0            99.3         7.45
12060     3676  36.0         6380.0            60.1         6.51
12068     7895  18.0        11561.0           105.6         8.25
12069     5731  34.0         3365.0            41.8         8.81
12070     7672  18.0         5189.0            59.3         7.21
12071     2707  36.0         9575.0            94.5         8.60
12073    11426  31.0         8611.0            79.4         6.75
12075      826  50.0         9445.0            98.2         6.65
12076     5948  47.0         6707.0            69.6         6.53
12077      385  27.0         6815.0            72.9         5.89
12081     8325  36.0         6509.0            63.6         6.83
12082     8138  41.0        12688.0           109.5         6.83
12092     5920  24.0        10548.0            94.9         5.61
12095     8759  37.0        12038.0           122.3         8.66
12096     5290  44.0         4104.0            41.3         9.97
12097    10383  26.0        13657.0           118.4         5.72
12099     6716  40.0         4349.0            42.3         7.60
12100     6592  23.0         2267.0            23.9         8.13
12101     8929  25.0        10563.0            85.0         7.88
12102    10971  39.0         8617.0            66.4         6.53
12104     8867  38.0         9025.0            82.2         8.01
12106    10542  37.0         6507.0            83.1         7.93
12108    11732  59.0         5970.0            60.9         8.54
12113     1942  31.0         5303.0            53.7         6.02
12114     3895  31.0         5660.0            57.6         5.96
12115    11769  35.0         4018.0            41.5         8.09
12118     7399  39.0         3877.0            49.6         9.68

       calories_burned   activity_segment  user_id_capped  age_capped  \
12009           2156.1  Moderately Active          1174.0        34.0
12011           1958.5     light activity          2489.0        35.0
12018           1997.9     Lightly Active         10283.0        45.0
12022           2185.9           Moderate          2228.0        29.0
12023           2297.2           Moderate          4641.0        43.0
12024           2238.3           Moderate          3506.0        21.0
12025           2301.8  Moderately Active          8549.0        31.0
12028           2319.7  moderately active         11223.0        34.0
12030           2418.7      HIGHLY ACTIVE         11788.0        46.0
12032           2226.3           Moderate          5794.0        36.0
12033           2286.5  Moderately Active           823.0        58.0
12035           2317.3           Moderate          4804.0        28.0
12039           2563.0      HIGHLY ACTIVE         10897.0        20.0
12047           2229.1              LIGHT          8102.0        28.0
12048           2629.2      Highly Active          6284.0        45.0
12049           2020.3              LIGHT          1990.0        39.0
12051           2404.9           Moderate          9134.0        38.0
12055           2697.8      Highly Active          7183.0        42.0
12056           1692.1     light activity          1417.0        36.0
12059           2444.2  Moderately Active          1514.0        18.0
12060           2208.3  moderately active          3676.0        36.0
12068           2643.2      HIGHLY ACTIVE          7895.0        18.0
12069           1965.7              LIGHT          5731.0        34.0
12070           2079.1     light activity          7672.0        18.0
12071           2424.8           Moderate          2707.0        36.0
12073           2085.5           Moderate         11426.0        31.0
12075           2245.5  Moderately Active           826.0        50.0
12076           2255.2           Moderate          5948.0        47.0
12077           2400.1  Moderately Active           385.0        27.0
12081           2090.5  moderately active          8325.0        36.0
12082           2476.1      HIGHLY ACTIVE          8138.0        41.0
12092           2359.1      HIGHLY ACTIVE          5920.0        24.0
12095           2457.9      Highly Active          8759.0        37.0
12096           1996.2     Lightly Active          5290.0        44.0
12097           2768.9      Highly Active         10383.0        26.0
12099           2042.5     light activity          6716.0        40.0
12100           1782.1              LIGHT          6592.0        23.0
12101           2525.4      highly active          8929.0        25.0
12102           2150.3  Moderately Active         10971.0        39.0
12104           2497.9  Moderately Active          8867.0        38.0
12106           2282.0           Moderate         10542.0        37.0
12108           2088.0     Lightly Active         11732.0        59.0
12113           2110.1     Lightly Active          1942.0        31.0
12114           2143.7     light activity          3895.0        31.0
12115           1821.5     light activity         11769.0        35.0
12118           2033.4     Lightly Active          7399.0        39.0

       steps_per_day_capped  active_minutes_capped  sleep_hours_capped  \
12009                9527.0                   85.7                6.94
12011                5078.0                   42.9                7.81
12018                5075.0                   36.2                7.33
12022                7298.0                   71.5                8.21
12023                8239.0                   83.3                5.46
12024                7799.0                   79.8                6.51
12025                7585.0                   79.7                5.73
12028                7697.0                   63.5                7.03
12030               11207.0                  102.4                6.31
12032                6935.0                   69.1                7.21
12033                8581.0                   83.4                6.94
12035                6000.0                   68.4                8.04
12039               10445.0                   99.7                6.15
12047                5629.0                   77.2                6.79
12048               11049.0                  106.4                6.94
12049                4012.0                   42.6                7.21
12051                9471.0                   94.1                7.83
12055               12215.0                  113.8                8.30
12056                1885.0                   32.2                7.48
12059                9015.0                   99.3                7.45
12060                6380.0                   60.1                6.51
12068               11561.0                  105.6                8.25
12069                3365.0                   41.8                8.81
12070                5189.0                   59.3                7.21
12071                9575.0                   94.5                8.60
12073                8611.0                   79.4                6.75
12075                9445.0                   98.2                6.65
12076                6707.0                   69.6                6.53
12077                6815.0                   72.9                5.89
12081                6509.0                   63.6                6.83
12082               12688.0                  109.5                6.83
12092               10548.0                   94.9                5.61
12095               12038.0                  122.3                8.66
12096                4104.0                   41.3                9.97
12097               13657.0                  118.4                5.72
12099                4349.0                   42.3                7.60
12100                2267.0                   23.9                8.13
12101               10563.0                   85.0                7.88
12102                8617.0                   66.4                6.53
12104                9025.0                   82.2                8.01
12106                6507.0                   83.1                7.93
12108                5970.0                   60.9                8.54
12113                5303.0                   53.7                6.02
12114                5660.0                   57.6                5.96
12115                4018.0                   41.5                8.09
12118                3877.0                   49.6                9.68

       calories_burned_capped
12009                  2156.1
12011                  1958.5
12018                  1997.9
12022                  2185.9
12023                  2297.2
12024                  2238.3
12025                  2301.8
12028                  2319.7
12030                  2418.7
12032                  2226.3
12033                  2286.5
12035                  2317.3
12039                  2563.0
12047                  2229.1
12048                  2629.2
12049                  2020.3
12051                  2404.9
12055                  2697.8
12056                  1692.1
12059                  2444.2
12060                  2208.3
12068                  2643.2
12069                  1965.7
12070                  2079.1
12071                  2424.8
12073                  2085.5
12075                  2245.5
12076                  2255.2
12077                  2400.1
12081                  2090.5
12082                  2476.1
12092                  2359.1
12095                  2457.9
12096                  1996.2
12097                  2768.9
12099                  2042.5
12100                  1782.1
12101                  2525.4
12102                  2150.3
12104                  2497.9
12106                  2282.0
12108                  2088.0
12113                  2110.1
12114                  2143.7
12115                  1821.5
12118                  2033.4
Data frame withiout duplicates:
        user_id   age  steps_per_day  active_minutes  sleep_hours  \
0            1  40.0        11524.0           100.7         7.82
1            2  34.0         2363.0            24.0         7.02
3            4  50.0         7875.0            90.5         7.59
4            5  33.0         8048.0            69.6         6.64
5            6  33.0         8541.0            75.8         6.81
...        ...   ...            ...             ...          ...
12110     1810  44.0        10868.0            97.2         7.25
12111     5665  30.0         5164.0            47.3         5.43
12112     4167  32.0         7928.0            82.9         7.15
12117    11011  37.0         7744.0            81.4         6.51
12119     1326  18.0        12543.0           108.5         9.61

       calories_burned   activity_segment  user_id_capped  age_capped  \
0               2594.2      Highly Active             1.0        40.0
1               1714.8              LIGHT             2.0        34.0
3               2290.2  moderately active             4.0        50.0
4               2238.8  moderately active             5.0        33.0
5               2305.2           Moderate             6.0        33.0
...                ...                ...             ...         ...
12110           2510.0      highly active          1810.0        44.0
12111           2057.1     Lightly Active          5665.0        30.0
12112           2354.2           Moderate          4167.0        32.0
12117           2214.7           Moderate         11011.0        37.0
12119           2551.6      HIGHLY ACTIVE          1326.0        18.0

       steps_per_day_capped  active_minutes_capped  sleep_hours_capped  \
0                   11524.0                  100.7                7.82
1                    2363.0                   24.0                7.02
3                    7875.0                   90.5                7.59
4                    8048.0                   69.6                6.64
5                    8541.0                   75.8                6.81
...                     ...                    ...                 ...
12110               10868.0                   97.2                7.25
12111                5164.0                   47.3                5.43
12112                7928.0                   82.9                7.15
12117                7744.0                   81.4                6.51
12119               12543.0                  108.5                9.61

       calories_burned_capped
0                      2594.2
1                      1714.8
3                      2290.2
4                      2238.8
5                      2305.2
...                       ...
12110                  2510.0
12111                  2057.1
12112                  2354.2
12117                  2214.7
12119                  2551.6

[11481 rows x 13 columns]

(11481, 13)

In [43]:
# In step 1, we run pd.unique(df['activity_segment'])
# 'Highly Active', 'LIGHT', 'light activity', 'moderately active',
#'Moderate', 'Moderately Active', 'HIGHLY ACTIVE', 'Lightly Active','highly active'
# We can use a map function to fix it

# Highly Active, HIGHLY ACTIVE, highly active -> Highly Active
# LIGHT, light activity, Lightly Active -> Lightly Active
# moderately active, Moderate, Moderately Active -> Moderately Active

df_standarized = df_without_duplicates
color_mapping = {
    'highly active': 'Highly Active',
    'light': 'Lightly Active',              
    'light activity': 'Lightly Active',
    'lightly active': 'Lightly Active',
    'moderately active': 'Moderately Active',
    'moderate': 'Moderately Active'
}

df_standarized['activity_segment'] = df_without_duplicates['activity_segment'].str.lower().str.strip().map(color_mapping)



pd.unique(df_standarized['activity_segment'])

C:\Users\jy441064\AppData\Local\Temp\ipykernel_24400\1037629571.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_standarized['activity_segment'] = df_without_duplicates['activity_segment'].str.lower().str.strip().map(color_mapping)

array(['Highly Active', 'Lightly Active', 'Moderately Active'],
      dtype=object)

In [50]:
Mid_age_sleep(df_standarized)

Mean age and sleep time for different activity status:
                         age  sleep_hours
activity_segment
Highly Active      49.881553     7.221456
Lightly Active     49.838174     7.322282
Moderately Active  49.623323     7.177214

Count for each activity status:
                   age  sleep_hours
activity_segment
Highly Active      515          515
Lightly Active     482          482
Moderately Active  969          969

Standard deviation for each activity status:
                        age  sleep_hours
activity_segment
Highly Active      4.378444     1.126980
Lightly Active     4.199638     1.032076
Moderately Active  4.170131     1.071193

After cleaning the dataset, the results became more consistent and easier to interpret. The activity categories were standardized from nine inconsistent labels into three clear groups: Highly Active, Moderately Active, and Lightly Active.  This removed fragmentation and combined counts correctly. Before cleaning, counts were split across similar labels and sometimes differed between variables  due to missing values or duplicates, making the results less reliable.  After cleaning, counts are consistent within each group, and the Moderately Active group has the largest sample size. The mean age and sleep hours remain very similar across groups both before and after cleaning,  maybe there's no significant difference by activity level. However, the standard deviation is now more reliable, showing similar variability across groups without distortion from inconsistent labels. Overall, data cleaning improves accuracy and ensures more reliable comparisons between groups.

________
# Part 2: Data Visualization and Data Preparation for Machine Learning Analysis
### Due Date : Sunday April 19th at 11:59pm
## Step 1 – Exploratory Data Analysis (EDA)
### Tasks

Create 4 visualizations:
1. Distribution of a numerical variable
2. Relationship between two numerical variables
3. Comparison across categories
4. Correlation visualization

Explain why you chose the visualization type and write a couple sentences analysis of what each visualization is telling you.

In [4]:
#Your code goes here

## Step 2 – Prepare Data for Machine Learning
### Tasks
1. Select features (X) and target (y).
2. Encode categorical variables if needed.
3. Split the dataset into training and testing sets
4. Clearly explain why you chose the target variable.

In [5]:
#Your code goes here

## Step 3 – Supervised Learning Models

### Choose one of the models below and train it:
1. Regression model (if dataset supports it)
2. Classification model
3. K-Nearest Neighbours (KNN)

### Tasks
1. Train the model on the training dataset.
2. Generate predictions on the test dataset.
3. Store predictions for comparison.

In [6]:
#Your code goes here

________
# Part 3: Machine Learning Analysis
### Due Date : Sunday May 3rd at 11:59pm

## Step 1 – Model Evaluation and Metrics
### Tasks
Evaluate the model:
   1. If a classification model was selected:
        - Calculate Accuracy
        - Generate the Confusion Matrix
        - Calculate Precision
        - Briefly explain what each metric tells you about model performance.
  1. If a Regression Model was selected:
        - Compute appropriate regression metrics (e.g., MAE, RMSE, R²).
        - Interpret what these values indicate about prediction quality.

In [41]:
#Your code goes here

## Step 2 – Overfitting, Underfitting, and Cross-Validation
### Tasks
1. Explain overfitting and underfitting using your results.
- Define overfitting and underfitting in your own words.
- Use your model’s training and test results to determine whether either issue is present.

2. Apply Cross-Validation:
- K-Fold Cross Validation
  
3. Compare and Interpret Results
- Choose an appropriate evaluation metric for your model (e.g., **accuracy, precision, recall, F1-score** for classification, or **R², RMSE** for regression).  
- Report the **mean cross-validation score** for your chosen metric.  
- Compare the cross-validation performance to your **test-set performance** using the same metric.  
- Discuss whether the model **generalizes well** or shows signs of **overfitting or underfitting** based on these results.

In [7]:
#Your code goes here

## Step 3 – Hyperparameter Tuning

### Tasks

1. Hyperparameter Optimization
- Use the model you chose before (regression or classification).
- Define a search space for the model’s key hyperparameters.
- Apply both:
  - **Grid Search** to test all combinations of hyperparameters.
  - **Bayesian Optimization** to efficiently explore the search space.
    - Briefly explain why you chose a particular prior or distribution for each hyperparameter (e.g., uniform, log-uniform).
- Identify the best hyperparameters from each method.
- Compare the results and check if both methods produce similar optimal values.

2. Fit the Final Model
- Train the model using the best hyperparameters found.
- Evaluate performance on both **training** and **test** datasets.
  - Comment on any differences in performance between training and test sets (e.g., whether the model is overfitting or well generalized).

3. Visualize Model Performance
- Create a **Predicted vs Actual** scatter plot:
  - Plot predicted values against true values.
  - Include a reference line (*y = x*) to assess prediction accuracy.
- Interpret how well the model performs based on the plot.

In [8]:
#Your code goes here